Some improvements to horizontal layout
Bnei-Baruch/galaxy-mobile pull request #19
Opened 2023-01-08 20:55 UTC by konstantin-mohin

@igala still don't get why we have additional 50.0 line 765

2023-01-11 01:23 UTC, igala commented on galaxy_mobile/lib/screens/streaming/streaming.dart
> -                        widget.isOnAir ? Colors.redAccent : Colors.transparent,
the border should be transparent and not green

2023-01-11 01:39 UTC, igala requested changes
looks good , just fix the border color

2023-01-12 08:21 UTC, konstantin-mohin commented on galaxy_mobile/lib/screens/streaming/streaming.dart
> -                        widget.isOnAir ? Colors.redAccent : Colors.transparent,
@igala yeah, right,  was debug with this color

2023-01-12 08:33 UTC, konstantin-mohin commented
@igala pushed

2023-01-14 00:47 UTC, merged